// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcsrLxbYj_8pX8H7fnVCRJmggAvVyEPso',
    appId: '1:45127216876:web:da38185d3c27bfa16fbfc9',
    messagingSenderId: '45127216876',
    projectId: 'apniride-59e18',
    authDomain: 'apniride-59e18.firebaseapp.com',
    storageBucket: 'apniride-59e18.firebasestorage.app',
    measurementId: 'G-JYP15HLHC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2qKQ-0-0G7-2GCDCgJXRFgbCoIkT9cLU',
    appId: '1:45127216876:android:7172ad19fedfb2eb6fbfc9',
    messagingSenderId: '45127216876',
    projectId: 'apniride-59e18',
    storageBucket: 'apniride-59e18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrA0q_12ZT6OZr-Aenw7eyGojMkYI6eBg',
    appId: '1:45127216876:ios:e9e4743e5dae85736fbfc9',
    messagingSenderId: '45127216876',
    projectId: 'apniride-59e18',
    storageBucket: 'apniride-59e18.firebasestorage.app',
    iosBundleId: 'com.example.apnirideFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrA0q_12ZT6OZr-Aenw7eyGojMkYI6eBg',
    appId: '1:45127216876:ios:e9e4743e5dae85736fbfc9',
    messagingSenderId: '45127216876',
    projectId: 'apniride-59e18',
    storageBucket: 'apniride-59e18.firebasestorage.app',
    iosBundleId: 'com.example.apnirideFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcsrLxbYj_8pX8H7fnVCRJmggAvVyEPso',
    appId: '1:45127216876:web:db0b290de54457956fbfc9',
    messagingSenderId: '45127216876',
    projectId: 'apniride-59e18',
    authDomain: 'apniride-59e18.firebaseapp.com',
    storageBucket: 'apniride-59e18.firebasestorage.app',
    measurementId: 'G-C8C3YF3RHK',
  );
}
